import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'About Us - SparkAI',
  description: 'Learn about SparkAI and our mission.',
};


export default function AboutUs() {
  return (
    <section className="relative">
      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        <div className="pt-32 pb-12 md:pt-40 md:pb-20">
          {/* Page header */}
          <div className="max-w-3xl mx-auto text-center pb-12 md:pb-20">
            <h1 className="h1">About Us</h1>
          </div>

          {/* About Us Content */}
          <div className="text-xl max-w-3xl mx-auto text-justify pb-12 md:pb-20">
            <p>
              SparkAI is a real-time interactive tool designed for both students and teachers. Our platform empowers students to enhance their academic performance through personalized tracking and management of their learning.
            </p>
            <p>
              Teachers also benefit from SparkAI, as it reduces their workload and improves student monitoring, allowing for timely guidance and support. The platform integrates modern pedagogical methods, including competitive learning, gamification, differentiated learning, and group-based learning.
            </p>
            <p>
              SparkAI follows the principles of Outcome-Based Education and incorporates built-in learning outcome analytics. It automates the creation of Course Portfolios, relieving teachers of additional administrative tasks.
            </p>
            <p>
              Leveraging Artificial Intelligence (AI), SparkAI provides students with insights into their current performance and predicts final grades. This enables proactive grade improvement strategies.
            </p>
          </div>

          <div className="max-w-3xl mx-auto text-justify pb-12 md:pb-20">
            <h3 className="h3" >SPARK-AI TOOL</h3>
            <ul>
              <li>Track</li>
              <li>Manage</li>
              <li>Improve your learning</li>
            </ul>

            <p>
              Give students real-time feedback on how well you are doing in the class and what your performance is after every class.
            </p>

            <h3 className="h3">Key Performance Indicators (KPI)</h3>
            <ul>
              <li>Attendance (on-time or late)</li>
              <li>Class Participation</li>
              <li>Quizzes</li>
              <li>Assignments</li>
              <li>Labs</li>
              <li>GBL</li>
            </ul>

            <h3 className="h3">Points to Grades</h3>
            <ul>
              <li>Points (competitive)</li>
              <li>Entering points</li>
              <li>Instantaneous Grade (IG)</li>
            </ul>

            <p>
              Max 350 = 20%
            </p>
            <p>
              Min 75 = 4.3%
            </p>
            <p>
              Slots = 17.5
            </p>

            <h3 className="h3">Student Perspective</h3>
            <ul>
              <li>Feel involved in their learning.</li>
              <li>Gratification after each class.</li>
              <li>Know they have control.</li>
              <li>Know what grade to expect for the course.</li>
            </ul>

            <h3 className="h3">Teacher’s Perspective</h3>
            <ul>
              <li>Reduce workload and pressure from teachers to track all students' performance.</li>
              <li>Allows teachers to give timely advice to students when alerts are generated by SparkAI.</li>
              <li>Have a better understanding of students' learning.</li>
              <li>Generate course portfolio.</li>
              <li>Better student satisfaction and feedback.</li>
            </ul>
          </div>

          <div className="max-w-3xl mx-auto text-justify pb-12 md:pb-20 text-center">
            <h3 className="h3 text-center">Summary</h3>
            <ul>
              <li>Empower Your Learning: SparkAI offers students a powerful platform to take control of their education and elevate their grades.</li>
              <li>Instant Feedback: Enjoy real-time feedback, providing you with ample opportunities to enhance your performance.</li>
              <li>User-Friendly and Fun: Experience an easy-to-use and enjoyable interface that makes learning a breeze.</li>
              <li>Seamless Integration: SparkAI seamlessly integrates into your teaching and learning journey for a smoother educational experience.</li>
            </ul>
          </div>

          <div className="max-w-3xl mx-auto text-justify pb-12 md:pb-20 text-center">
  <h3 className="h3 text-center">Easy Steps to Get Started</h3>
  <ol>
    <li><strong>Download SparkAI:</strong></li>
    <ul>
    <li>
  For iPhone users, visit the Apple Store:{' '}
  <Link href="https://apps.apple.com/us/app/spark-ai-sle/id6450753287">
    <strong>Download SparkAI</strong>
  </Link>
</li>
<li>
  For Android users, head to the Google Play Store:{' '}
  <Link href="https://play.google.com/store/apps/details?id=com.handabots.sparkai&pcampaignid=web_share">
    <strong>Download SparkAI</strong>
  </Link>
</li>

    </ul>
    <li><strong>New Student Registration:</strong></li>
    <ul>
      <li>Sign up as a new student user.</li>
    </ul>
    <li><strong>Sign In:</strong></li>
    <ul>
      <li>Log in to your SparkAI account.</li>
    </ul>
    <li><strong>Join a Course:</strong></li>
    <ul>
      <li>Navigate to the ‘Join Course’ section.</li>
    </ul>
    <li><strong>Enter Teacher’s Email:</strong></li>
    <ul>
      <li>Provide your teacher’s email address (e.g., youremail@here.com).</li>
      <li>Scan QR code to join course.</li>

    </ul>
    <li><strong>Course Enrollment:</strong></li>
    <ul>
      <li>Join the course.</li>
    </ul>
    <li><strong>Approval Pending:</strong></li>
    <ul>
      <li>Wait for your teacher’s approval.</li>
    </ul>
    <li><strong>Course Access:</strong></li>
    <ul>
      <li>Once approved, access your registered course and start your learning journey!</li>
    </ul>
  </ol>
</div>



          <div className="flex flex-wrap -mx-3 mt-6">
            <div className="w-full px-3">
              <button className="btn text-white bg-purple-600 hover-bg-purple-700 w-full">
                <Link href="/contactus">Contact Us</Link>
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
  
}
